version: "3.8"

services:
  db-mysql:
    image: mysql:8.3
    container_name: go-mysql
    environment:
      MYSQL_DATABASE: products
      MYSQL_USER: robot
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: go-mysql
    ports:
      - "3306:3306"
    volumes:  
      - G:/DB/mysql/products:/var/lib/mysql
    restart: always  